include: package:very_good_analysis/analysis_options.7.0.0.yaml
analyzer:
  errors:
    avoid_redundant_argument_values: ignore
    avoid_print: ignore
    no_default_cases: ignore
  exclude:
    - build/**
linter:
  rules:
    file_names: false
