include: package:very_good_analysis/analysis_options.7.0.0.yaml
analyzer:
  errors:
    avoid_redundant_argument_values: ignore
    avoid_print: ignore
    no_default_cases: ignore
    avoid_catches_without_on_clauses: ignore
    lines_longer_than_80_chars: ignore
    avoid_dynamic_calls: ignore
    avoid_catching_errors: ignore
    document_ignores: ignore
    one_member_abstracts: ignore
    cascade_invocations: ignore
  exclude:
    - build/**
linter:
  rules:
    file_names: false
